baseURL = "http://aparna-k.com/"
languageCode = "en-us"
title = "Datascope"
theme = "ananke"
[params]
  favicon= 'favicon.ico'
  description= "Looking through a Datascope"
  author= "Aparna Korattyswaroopam"
  copyright= "2017"
  background_color_class = "bg-black"
  featured_image = "/images/custom_hero.png"