baseURL = "https://aparna-k.com/"
languageCode = "en-us"
title = "Datascope"
theme = "hyde-hyde"
[params]
  favicon= 'favicon.ico'
  description= "Prediction is risky, especially when it involves the future. - Niels Bohr"
  author= "Aparna Korattyswaroopam"
  copyright= "2017"
  background_color_class = "bg-black"
  featured_image = "/images/custom_hero.png"